# File: docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "2942:2942"
    env_file:
      - .env
    environment:
      - POSTGRES_HOSTNAME=db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      # This is the key change:
      # It maps the postgres-data folder on your NAS to the data directory inside the container.
      - ./postgres-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5434:5432"

# We no longer need the top-level 'volumes' key, so it has been removed.