# File: docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      # Changed host port from 8000 to 8001 to avoid conflicts
      - "8001:5000"
    env_file:
      - .env
    environment:
      # This tells the web container to find the database at the hostname 'db'
      - POSTGRES_HOSTNAME=db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      # Changed host port from 5433 to 5434 to avoid conflicts
      - "5434:5432"

volumes:
  postgres_data:

