version: '3.8'

services:
  web:
    build: .
    container_name: aquajal_app
    restart: unless-stopped
    ports:
      - "2942:2942"
    environment:
      # Ensure you change this in a real production environment
      - SECRET_KEY=your_very_secret_key_change_me 
      - DATABASE_URL=sqlite:////app/data/app.db
    volumes:
      # This maps the 'data' folder on your computer to /app/data in the container
      # It will persist your SQLite database.
      - ./data:/app/data
      # This maps the 'uploads' folder on your computer to the container's upload path
      # It will persist all user-uploaded files.
      - ./app/static/uploads:/app/app/static/uploads
    # The command is now handled by the entrypoint script