# migrations/versions/xxxxxxxxxxxx_add_customer_type_to_customer_model.py

"""Add customer_type to Customer model

Revision ID: 017dc3402d21 # Or your specific ID
Revises: 94c2fee16e97 # The previous revision ID
Create Date: ...

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017dc3402d21' # Or your specific ID
down_revision = '94c2fee16e97' # The previous revision ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        # ADD server_default='customer' HERE
        batch_op.add_column(sa.Column('customer_type', sa.String(length=10), nullable=False, server_default='customer'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('customer_type')

    # ### end Alembic commands ###