"""Add manufacture_price to SupplierProduct

Revision ID: 072fd5b3b11f
Revises: e8c9080c9454
Create Date: 2025-10-16 01:25:46.750867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072fd5b3b11f'
down_revision = 'e8c9080c9454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacture_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_product', schema=None) as batch_op:
        batch_op.drop_column('manufacture_price')

    # ### end Alembic commands ###
