"""Add stock management to Business model

Revision ID: 10d3af5df8a8
Revises: 7504c727ca0c
Create Date: 2025-10-11 16:52:37.778173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d3af5df8a8'
down_revision = '7504c727ca0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jar_stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dispenser_stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('dispenser_stock')
        batch_op.drop_column('jar_stock')

    # ### end Alembic commands ###
