"""Add supplier and procurement models

Revision ID: 1a2a421b3afd
Revises: cb84e6ce92f7
Create Date: 2025-10-14 20:40:33.676181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2a421b3afd'
down_revision = 'cb84e6ce92f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_supplier_profile_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_profile'))
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_purchase_order_business_id_business')),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_profile.id'], name=op.f('fk_purchase_order_supplier_id_supplier_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order'))
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_order_date'), ['order_date'], unique=False)

    op.create_table('supplier_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_profile.id'], name=op.f('fk_supplier_product_supplier_id_supplier_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_product'))
    )
    op.create_table('purchase_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], name=op.f('fk_purchase_order_item_order_id_purchase_order')),
    sa.ForeignKeyConstraint(['product_id'], ['supplier_product.id'], name=op.f('fk_purchase_order_item_product_id_supplier_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_order_item')
    op.drop_table('supplier_product')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_order_date'))

    op.drop_table('purchase_order')
    op.drop_table('supplier_profile')
    # ### end Alembic commands ###
