"""Add subscription fields to Business model

Revision ID: 1ede9f8d3a8b
Revises: c28c53dea117
Create Date: 2025-10-12 14:20:31.724304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ede9f8d3a8b'
down_revision = 'c28c53dea117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon')),
    sa.UniqueConstraint('code', name=op.f('uq_coupon_code'))
    )
    op.create_table('subscription_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('regular_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plan')),
    sa.UniqueConstraint('name', name=op.f('uq_subscription_plan_name'))
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_payment_business_id_business')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_business_subscription_plan_id_subscription_plan'), 'subscription_plan', ['subscription_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_business_subscription_plan_id_subscription_plan'), type_='foreignkey')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('subscription_plan_id')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_status')

    op.drop_table('payment')
    op.drop_table('subscription_plan')
    op.drop_table('coupon')
    # ### end Alembic commands ###
