"""add payment status to logs and sales

Revision ID: 2b1a3c4d5e6f
Revises: 9fb08846a8a3
Create Date: 2025-10-14 01:28:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1a3c4d5e6f'
down_revision = '9fb08846a8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('product_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sale', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
    # ### end Alembic commands ###