"""Add subscription plan link to payment

Revision ID: 3b0039ba6d9a
Revises: 1ede9f8d3a8b
Create Date: 2025-10-12 15:14:29.044503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0039ba6d9a'
down_revision = '1ede9f8d3a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payment_subscription_plan_id_subscription_plan'), 'subscription_plan', ['subscription_plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_subscription_plan_id_subscription_plan'), type_='foreignkey')
        batch_op.drop_column('subscription_plan_id')

    # ### end Alembic commands ###
