"""add origin to daily log

Revision ID: 49ccdc1f5687
Revises: 931bd0819b13
Create Date: 2025-10-14 03:05:42.486532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ccdc1f5687'
down_revision = '931bd0819b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=20), server_default='staff_log', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_log', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
