"""Add attendance jar count thresholds to Business model

Revision ID: 5658261d88ba
Revises: b938e8ad3e7d
Create Date: 2025-10-13 01:34:22.583707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5658261d88ba'
down_revision = 'b938e8ad3e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_day_jar_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('half_day_jar_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('half_day_jar_count')
        batch_op.drop_column('full_day_jar_count')

    # ### end Alembic commands ###
