"""Add dispensers to event bookings

Revision ID: 658ca2ea9077
Revises: 3b0039ba6d9a
Create Date: 2025-10-12 17:20:47.901958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658ca2ea9077'
down_revision = '3b0039ba6d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispensers_booked', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dispensers_returned', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_booking', schema=None) as batch_op:
        batch_op.drop_column('dispensers_returned')
        batch_op.drop_column('dispensers_booked')

    # ### end Alembic commands ###
