"""Add upi_id to Business model

Revision ID: 674b8207ea40
Revises: d4733cfd73eb
Create Date: 2025-10-22 00:27:02.283535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674b8207ea40'
down_revision = 'd4733cfd73eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('upi_id')

    # ### end Alembic commands ###
