"""Add delivery_date and invoice_number to purchase order

Revision ID: 6cbd9e68e3cb
Revises: 1a2a421b3afd
Create Date: 2025-10-14 23:14:20.246030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbd9e68e3cb'
down_revision = '1a2a421b3afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_purchase_order_invoice_number'), ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_purchase_order_invoice_number'), type_='unique')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###
