"""Add staff details fields to User model

Revision ID: 8374ff7a2bf5
Revises: 10d3af5df8a8
Create Date: 2025-10-11 17:22:39.255854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8374ff7a2bf5'
down_revision = '10d3af5df8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('id_proof_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id_proof_filename')
        batch_op.drop_column('address')
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###
