"""add due_amount to customer

Revision ID: 931bd0819b13
Revises: 2b1a3c4d5e6f
Create Date: 2025-10-14 02:03:27.270510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931bd0819b13'
down_revision = '2b1a3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('due_amount')

    # ### end Alembic commands ###
