"""Add completion_date to PurchaseOrder

Revision ID: 94c2fee16e97
Revises: dbea34c9b8cb
Create Date: 2025-10-17 03:02:37.799727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c2fee16e97'
down_revision = 'dbea34c9b8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_column('completion_date')

    # ### end Alembic commands ###
