"""Add low_stock_threshold to Business

Revision ID: 960a3ee82ae6
Revises: 924a56ebb6ac
Create Date: 2025-10-15 23:13:34.613412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960a3ee82ae6'
down_revision = 'b026caffbdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('low_stock_threshold')

    # ### end Alembic commands ###
