"""Add invoice tables

Revision ID: 9fb08846a8a3
Revises: 9e3896a85936
Create Date: 2025-10-13 21:31:04.143133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb08846a8a3'
down_revision = '9e3896a85936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_invoice_business_id_business')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_invoice_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoice_invoice_number'))
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_item_invoice_id_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_item')
    op.drop_table('invoice')
    # ### end Alembic commands ###
