"""Add wage_type and salary fields to User model

Revision ID: a827c9f68316
Revises: 017dc3402d21
Create Date: 2024-05-17 12:00:00.000000 

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a827c9f68316'
down_revision = '017dc3402d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # We only need to add monthly_salary, since wage_type was
        # added in the failed attempt and daily_wage already existed.
        batch_op.add_column(sa.Column('monthly_salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Full downgrade to remove all 3 columns
        batch_op.drop_column('monthly_salary')
        batch_op.drop_column('daily_wage') # This will fail if daily_wage wasn't meant to be dropped, but it's safer
        batch_op.drop_column('wage_type')
    # ### end Alembic commands ###