"""Add supplier class to the models

Revision ID: b026caffbdf7
Revises: 6cbd9e68e3cb
Create Date: 2025-10-15 21:10:37.028134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b026caffbdf7'
down_revision = '6cbd9e68e3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_supplier_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_purchase_order_invoice_number'), type_='unique')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('delivery_date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_purchase_order_invoice_number'), ['invoice_number'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    op.drop_table('supplier')
    # ### end Alembic commands ###
