"""Add owner name and email to business model

Revision ID: b938e8ad3e7d
Revises: 1554d1acf6a6
Create Date: 2025-10-12 23:08:14.403823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b938e8ad3e7d'
down_revision = '1554d1acf6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_business_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_email'))
        batch_op.drop_column('email')
        batch_op.drop_column('owner_name')

    # ### end Alembic commands ###
