"""add note to customer

Revision ID: cb84e6ce92f7
Revises: 49ccdc1f5687
Create Date: 2025-10-14 10:59:48.014276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb84e6ce92f7'
down_revision = '49ccdc1f5687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
