"""Add customer login and booking system

Revision ID: d2909f109667
Revises: 8374ff7a2bf5
Create Date: 2025-10-11 20:59:46.863407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2909f109667'
down_revision = '8374ff7a2bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paid_to_manager', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('delivery_timestamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('delivered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['user.id'], name=op.f('fk_event_booking_confirmed_by_id_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_event_booking_customer_id_customer')),
    sa.ForeignKeyConstraint(['delivered_by_id'], ['user.id'], name=op.f('fk_event_booking_delivered_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_booking'))
    )
    with op.batch_alter_table('event_booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_booking_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_booking_status'), ['status'], unique=False)

    op.create_table('jar_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('delivery_timestamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('delivered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_jar_request_customer_id_customer')),
    sa.ForeignKeyConstraint(['delivered_by_id'], ['user.id'], name=op.f('fk_jar_request_delivered_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jar_request'))
    )
    with op.batch_alter_table('jar_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jar_request_status'), ['status'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('jar_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jar_request_status'))

    op.drop_table('jar_request')
    with op.batch_alter_table('event_booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_booking_status'))
        batch_op.drop_index(batch_op.f('ix_event_booking_event_date'))

    op.drop_table('event_booking')
    # ### end Alembic commands ###
