"""Add house_number to Customer model

Revision ID: d4733cfd73eb
Revises: a827c9f68316
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4733cfd73eb'
down_revision = 'a827c9f68316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        try:
            batch_op.add_column(sa.Column('house_number', sa.String(length=120), nullable=True))
            print("Successfully added 'house_number' column.")
        except Exception as e:
            print(f"Skipping add_column('house_number'): {e}") # It's ok if it already exists
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        try:
            batch_op.drop_column('house_number')
        except Exception as e:
            print(f"Could not drop 'house_number': {e}")
    # ### end Alembic commands ###
