"""Add house_number to Customer model

Revision ID: d4733cfd73eb
Revises: a827c9f68316
Create Date: 2025-10-21 10:12:49.173881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4733cfd73eb'
down_revision = 'a827c9f68316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('house_number')

    # ### end Alembic commands ###
