"""Add house_number to Customer model

Revision ID: d4733cfd73eb
Revises: a827c9f68316
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4733cfd73eb'
down_revision = 'a827c9f68316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually edited to handle inconsistent prod database.
    # Logs show 'house_number' column already exists.
    # We 'pass' here so Alembic can mark this migration as
    # complete and the app can start.
    print("Skipping add_column('house_number') as it already exists.")
    pass
    
    # Original auto-generated code (commented out):
    # with op.batch_alter_table('customer', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('house_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        try:
            batch_op.drop_column('house_number')
        except Exception as e:
            print(f"Could not drop 'house_number': {e}")
    # ### end Alembic commands ###
