"""Add PushSubscription table for notifications

Revision ID: dbea34c9b8cb
Revises: 072fd5b3b11f
Create Date: 2025-10-17 02:44:23.777255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbea34c9b8cb'
down_revision = '072fd5b3b11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_push_subscription_customer_id_customer')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_push_subscription_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscription'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
