"""add confirmation for bookings

Revision ID: e5ed73cd38b3
Revises: 95cf0fbab81a
Create Date: 2025-10-12 01:15:38.743106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ed73cd38b3'
down_revision = '95cf0fbab81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('jars_returned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('collected_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_event_booking_collected_by_id_user'), 'user', ['collected_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_booking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_booking_collected_by_id_user'), type_='foreignkey')
        batch_op.drop_column('collected_by_id')
        batch_op.drop_column('final_amount')
        batch_op.drop_column('jars_returned')
        batch_op.drop_column('collection_timestamp')

    # ### end Alembic commands ###
