"""Add low_stock_threshold_dispenser to Business

Revision ID: e8c9080c9454
Revises: 960a3ee82ae6
Create Date: 2025-10-15 23:31:04.243348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c9080c9454'
down_revision = '960a3ee82ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold_dispenser', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('low_stock_threshold_dispenser')

    # ### end Alembic commands ###
